name: Merge main Deploy Production
"on":
  push:
    branches:
      - main
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Build Purescript App
        uses: haniker-dev/build-purescript@main
        with:
          node-version: "16.x"
          build-dir: "dist"
          public-dir: "public"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HANIKER_WEBSITE }}"
          channelId: live
          projectId: haniker-website

      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.3
        id: psi
        with:
          url: "https://www.haniker.dev"
          threshold: 90
          strategy: mobile
          key: ${{ secrets.PAGE_SPEED_API_KEY }}
