name: PR Deploy Preview
"on": pull_request
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Build Purescript App
        uses: haniker-dev/build-purescript@main
        with:
          node-version: "16.x"
          build-dir: "dist"
          entry-html: "public/index.html"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HANIKER_WEBSITE }}"
          projectId: haniker-website
